#!/bin/bash
set -x
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
./client.py "$@" &
