#!/usr/bin/python
import time
from daemon import runner
import Pyro4


class App():
    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/tty'
        self.stderr_path = '/dev/tty'
        self.pidfile_path = '/tmp/foo2.pid'
        self.pidfile_timeout = 5

    def run(self):
        print("Running the name server!")
        Pyro4.naming.startNSloop()
        print("Done Running the name server!")


app = App()
daemon_runner = runner.DaemonRunner(app)
daemon_runner.do_action()
