#!/usr/bin/python
import time
from daemon import runner
import Pyro4
from Queue import Queue

class Messages(object):
    _q = Queue()
    def put(self, msg):
        print 'adding msg', msg
        self._q.put(msg)
        print 'q now size', self._q.qsize()

        raise Exception("mark of the beast")

    def get(self):
        return self._q.get()



messages = Messages()

class App():



    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/tty'
        self.stderr_path = '/dev/tty'
        self.pidfile_path =  '/tmp/foo.pid'
        self.pidfile_timeout = 5
    def run(self):
#       daemon=Pyro4.Daemon()
#       ns=Pyro4.locateNS()
#       uri=daemon.register(messages)
#       ns.register("messages",uri)
#       daemon.requestLoop(app_func);
        
        Pyro4.Daemon.serveSimple(
            {
                messages: "messages"
            },
            ns=True, verbose=True)        
        print("Howdy!  Gig'em!  Whoop!")
           # time.sleep(10)

app = App()
daemon_runner = runner.DaemonRunner(app)
daemon_runner.do_action()
